"""Initial Migration

Revision ID: dd25129e1eff
Revises: 0c9a5abdc1b1
Create Date: 2020-05-15 03:29:25.620913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd25129e1eff'
down_revision = '0c9a5abdc1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('email', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'email')
    # ### end Alembic commands ###
